### ISSUE TITLE
CSS style modal within modal

### ISSUE THREAD

**Issue by George2215** [pencilpix/vue2-clock-picker#4]
I am using this component within a modal, but the modal of the clock is not shown. how can I modify the css style to show the clock

my CSS style for the first modal

```
.modal-content .modal-body {
        position: relative;
        padding: 20px 10px;
    }
    .modal-content{
        width: 100% !important;        
    }
    .mostrar{
        display: list-item !important;
        opacity: 1 !important;
        position: absolute !important;
        background-color: #3c29297a !important;        
    }
    .div-error{
        display: flex;
        justify-content: center;
    }
    .text-error{
        color: red !important;
        font-weight: bold;
    }
```
I appreciate your help

**Comment by pencilpix** [comment]
@George2215 You can take a look at the styles source code of the dialog [here](https://github.com/pencilpix/vue2-clock-picker/blob/master/src/components/ClockPickerDialog.vue#L299)

I think the problem rely on z-index try to inspect your modal z-index and if it's higher that clock picker dialog z-index try to modify it according to the classes `.clock-picker__dialog-drop` & `.clock-picker__dialog-body`. the current values are `200` and `201` respectively
also you can override the whole styles

**Comment by George2215** [comment]
thank you
