### ISSUE TITLE
Wrong canvas font used first time picker is opened. 

### ISSUE THREAD

**Issue by mortenscheel** [pencilpix/vue2-clock-picker#6]
Hi,

I'm having a weird issue with the fonts used to draw on the canvas. 
I'm not using a Material theme, but I've imported the Roboto font.
The first time a picker is displayed, it uses the wrong font (default serif, Times New Roman I guess) for the numbers.
When closed, and opened again, it uses the correct font (Roboto).
With multiple pickers on the same page, the issue doesn't occur with all of them - only the first one opened is affected.

Is this a bug, or am I missing a step?

**Comment by pencilpix** [comment]
Hi,
can you share the setup you use and how you imported roboto font, since I installed on this [bin](https://jsbin.com/jeresenogo/1/edit?html,output) and it works fine, or even check the bin if the same issue is still happening. but really for me it works just fine

**Comment by mortenscheel** [comment]
Hey, thanks for responding.
I just tried out you bin, and it exhibits the exact same issue.
In case it's relevant, I'm using Chrome on Windows 10.

Here's a partial screenshot from the first time the picker opens:
![image](https://user-images.githubusercontent.com/6514342/47259180-36920900-d4a6-11e8-8a0a-4c5b82b51262.png)

And after that:
![image](https://user-images.githubusercontent.com/6514342/47259189-51647d80-d4a6-11e8-8010-aeb41c15be47.png)

**Comment by pencilpix** [comment]
@mortenscheel sorry about late reply. really I don't get why is this happening but I can do something else, what if we make the font family of the canvas is a prop and you just use the font that is already rendered in the whole page before you open the clock picker ?

**Comment by mortenscheel** [comment]
Sure, sounds like a good idea. While you’re at it, maybe it would make sense to allow customization of the font weights as well?

**Comment by pencilpix** [comment]
solved at `v0.1.5`
